//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webbhtp_18
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Product
    {
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public Nullable<int> CategoryProductId { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> PriceSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsNew { get; set; }
        public bool IsBestSeller { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tb_CategoryProduct tb_CategoryProduct { get; set; }
    }
}
